# FieldDesk AI 工单状态定义


DRAFT = "DRAFT"

WAITING_REVIEW = "WAITING_REVIEW"

AI_ANALYZING = "AI_ANALYZING"

TECHNICIAN_CHECK = "TECHNICIAN_CHECK"

CRM_RUNNING = "CRM_RUNNING"

WAITING_CONFIRMATION = "WAITING_CONFIRMATION"

COMPLETED = "COMPLETED"

FAILED = "FAILED"